parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: blog
    database_user: root
    database_password: weweb
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5105b892a157eaac7518074792ed41d52
    database_path: null
