parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: newspaper
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: group10weweb
    mailer_password: fall2012cmpt470
    locale: en
    secret: 8cbb584ab3b563e794dd501b1879c229
    database_path: null
